### ISSUE TITLE
How to define query parameter limits?

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-spec#191]
How can I have a query parameter that has more than just `type`? Here is my query parameter:
```yaml
- name: limit
  in: query
  description: number of pets to return
  type: integer
```

But I want to limit query param to be no less than 10 and no more than 1000. How can I do that?
