### ISSUE TITLE
Is possible to do a nested require on definitions?

### ISSUE THREAD

**Issue by diegobernardes** [swagger-api/swagger-spec#242]
Look at this example:

```yaml
definitions:
  MonitoredPoint:
    required:
      - id
      - name
      - user_id
      - created_at
      - tracker
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      user_id:
        type: integer
        format: int64
      created_at: 
        type: string
        format: 'date-time'
      tracker: 
        id: integer
        code: string
```

Could i do a require in the inner properties of tracker?
Something like this:

```yaml
    required:
      - 'tracker.id'
      - 'tracker.code'
```
