### ISSUE TITLE
Definitions object does not take 'default' at root

### ISSUE THREAD

**Issue by fishermand46** [swagger-api/swagger-spec#246]
From the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swaggerObject), a definition object is just a named schema object. However, when I try to add the 'default' schema property, the swagger validator complains with `Void does not allow a value`.

Example:
```yaml
definitions:
  Model:
    default: |-
      {
        'id': 3
      }
    properties:
      id:
        type: integer
        format: int32
```

**Comment by webron** [comment]
When you say 'it complains', what's 'it'?

**Comment by fishermand46** [comment]
Swagger editor, so I presume the swagger parser as we well.

**Comment by webron** [comment]
In that case, you open the issue on the swagger-editor project (though I believe it may derive from swagger-tools). 

As a side note, it looks like you're trying to set the default value to some json format - keep in mind that's not a valid json (`id` needs to be surrounded by `"`).

**Comment by whitlockjc** [comment]
The equivalent JSON is as follows, for those not YAML savvy:

```json
{
  "definitions": {
    "Model": {
      "default": "{\n  'id': 3\n}",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}
```

While I doubt this is intended, it still fails even when the YAML is this:

```yaml
definitions:
  Model:
    default:
        id: 3
    properties:
      id:
        type: integer
        format: int32
```
It seems that [swagger-tools](https://github.com/apigee-127/swagger-tools) is the culprit.  _(swagger-editor uses swagger-tools for the Swagger document validation)_  Basically, we validate all `default` values and it seems that for models, having a `default` value isn't supported.  I will file a bug.
