### ISSUE TITLE
Annotating query parameter cardinality

### ISSUE THREAD

**Issue by logicbomb** [swagger-api/swagger-spec#409]
The HTTP spec lets us specify the same querystring parameter multiple times.  Often our app only expects it to be specified once.  It'd be nice to have a boolean attribute `multiple` that indicates the number of times the API expects to see certain querystring params.

Currently I capture this information in the description field, but it can't be enforced there.  Here's an example of how I think it would be used

```
parameter:
  group:
    type: string
    multiple: true
    description: filter results by specified groups
  before:
     type: string
     format: ISO8601
     multiple: false
     description: max time for results
```
